### ISSUE TITLE
Area process failing on OSGeo-Live 10.5

### ISSUE THREAD

**Issue by ldesousa** [geopython/pywps-flask#33]
# Description

Execution of the Area process in the OSGeo-Live system fails when it tries to use `ogr2ogr` with this message:

> Process error: area.py._handler Line 38 Command '['ogr2ogr', '-f', 'geojson', '/tmp/tmpe_ecJE/input.geojson', '/home/user/git/pywps-flask/workdir/pywps_process_yCeL0o/tmpy0J6ne']' returned non-zero exit status 1

# Environment

- operating system: OSGeo-Live 10.5 (Lubuntu 10.5)
- Python version: 2.7
- PyWPS version: 4.0
- source/distribution
 - [x] git clone
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify): 
- web server
 - [ ] Apache/mod_wsgi
 - [ ] CGI
 - [x] other (please specify): Flask

# Steps to Reproduce
[http://localhost:5000/wps?&REQUEST=Execute&IDENTIFIER=area&SERVICE=WPS&VERSION=1.0.0&DATAINPUTS=layer=https%3A%2F%2Fraw.githubusercontent.com%2FPyWPS%2Fpywps-workshop%2Fmaster%2Fdata%2Frailroads.gml](http://localhost:5000/wps?&REQUEST=Execute&IDENTIFIER=area&SERVICE=WPS&VERSION=1.0.0&DATAINPUTS=layer=https%3A%2F%2Fraw.githubusercontent.com%2FPyWPS%2Fpywps-workshop%2Fmaster%2Fdata%2Frailroads.gml)
# Additional Information

**Comment by tomkralidis** [comment]
Note that PyWPS has been retired from OSGeo-Live (see https://trac.osgeo.org/osgeo/ticket/1886).  Suggest we focus on PyWPS 4 inclusion instead.

**Comment by ldesousa** [comment]
This is a general problem affecting all processes, on this system processes are unable to access the `file` objects associated with `ComplexInput` instances. This could be happening because I installed PyWPS with `pip`, therefore the `workdir` is being created outside the user area.
