### ISSUE TITLE
Xerces version must be bumped to 3.2.1

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pywps-flask#38]
# Description
Dockers are using xerces version 3.2.0, which has been removed from the Apache server. New version is 3.2.1
# Environment
Docer
- operating system:
- Python version:
- PyWPS version:
- source/distribution
 - [ ] git clone
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify): 
- web server
 - [ ] Apache/mod_wsgi
 - [ ] CGI
 - [ ] other (please specify): 

# Steps to Reproduce
docker build -t pywps .
# Additional Information

**Comment by lazaa32** [comment]
Should be fixed in #45

**Comment by jorgejesus** [comment]
Fixed on #45 and being implemented on #49
