### ISSUE TITLE
Relative path to SQLite database does not function on OSGeo-Live

### ISSUE THREAD

**Issue by ldesousa** [geopython/pywps-flask#40]
# Description

For pywps-flask to work on OSGeo-Live I must modify the database path to a absolute path, e.g.:
`database=sqlite:////home/user/pywps-flask/logs/pywps-logs.sqlite3`

Could be a bug with SQLAlchemy, or SQLite...

# Environment

- operating system: OSGeo/Live 11
- Python version: 2.7
- PyWPS version: 4.0.0
- source/distribution
 - [ ] git clone
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [x] other (please specify): ubuntugis
- web server
 - [ ] Apache/mod_wsgi
 - [ ] CGI
 - [x] other (please specify): Flask 

# Steps to Reproduce

Clone pywps-flask into OSGeo-Live, run the demo:
`python demo.py`

Then try an Execute request, e.g.:
`http://localhost:5000/wps?service=WPS&version=1.0.0&request=Execute&identifier=say_hello&dataInputs=name=Toto`

# Additional Information

**Comment by jorgejesus** [comment]
Tested with `pywps-4.2.1` that has the following database string: `database=sqlite:///logs/pywps-logs.sqlite3` and with OsGEO 12.0 and using the execute request: 
```
http://localhost:5000/wps?service=WPS&version=1.0.0&request=Execute&identifier=say_hello&dataInputs=name=Toto
 ```

The sqlite was using the relative path to `./log/pywps-logs.sqlite3`

Everything seems OK, closing ticket
