### ISSUE TITLE
Docker: pulling image fails due to lack of latest tag

### ISSUE THREAD

**Issue by ruimaciel** [geopython/pywps-flask#43]
PyWPS lists `docker pull pywps/flask-alpine` as the docker pull command, but that command assumes the availability of a "latest" tag.  As there is no latest tag neither in `pywps/flask-alpine` nor in `pywps/flask-ubuntu` then the docker pull command fails with the following error message:

    rmam:docker_pywps$ docker pull pywps/flask-alpine
    Using default tag: latest
    Error response from daemon: manifest for pywps/flask-alpine:latest not found

**Comment by zoot-inge** [comment]
also for pywps/flask-ubuntu:16.0.4

why pywps/... and not geopython/...?

**Comment by jorgejesus** [comment]
@zoot-wur  We tried some time ago and there was some issue on the owership/bug on the docker repository. Created a ticket #54 didnt noticed that the pywps images where so outdated
